<% require 'kitchen-sync' %>
---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-west-2
  subnet_id: subnet-19ac017c
  availability_zone: us-west-2a

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-14.04
  driver_plugin: ec2
  driver_config:
    username: ubuntu
    flavor_id: c4.8xlarge
    image_id: ami-5189a661
    block_device_mappings:
    - ebs_device_name: '/dev/sdi'
      ebs_volume_type: gp2
      ebs_virtual_name: chef-web-docs
      ebs_volume_size: 40
      ebs_delete_on_termination: true
  run_list:
    - recipe[apt]

suites:
- name: builder
  run_list:
    - recipe[docs-builder]
  attributes:
    docs-builder:
      ssh_key: "<%= File.read(File.join(Dir.home, '.ssh', 'id_rsa')).gsub(/\n/, '::::::::') %>"
      artifact_name: chef-web-docs-testing
      aws_access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
